summary: PCA File Uploader
value:
  css:
    buttoncomponent:
      button:
        class: ''
        style: ''
      container:
        class: ''
        style: ''
    containercomponent:
      container:
        class: ''
        style: ''
    jobidflowstatuscomponent:
      container:
        class: ''
        style: ''
      header:
        class: ''
        style: ''
    s3fileinputcomponent:
      container:
        class: ''
        style: ''
  fullscreen: false
  grid:
    - '12':
        fixed: false
        fullHeight: false
        h: 2
        w: 12
        x: 0
        y: 0
      '3':
        fixed: false
        fullHeight: false
        h: 2
        w: 6
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: containercomponent
        actions: []
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 9
        w: 12
        x: 0
        y: 2
      '3':
        fixed: false
        fullHeight: true
        h: 8
        w: 2
        x: 0
        y: 2
      id: c
      data:
        id: c
        type: s3fileinputcomponent
        actions: []
        configuration:
          type:
            type: oneOf
            configuration:
              s3:
                acceptedFileTypes:
                  type: static
                  value:
                    - text/csv
                allowMultiple:
                  type: static
                  value: false
                disabled:
                  type: static
                  value: false
                pathTemplate:
                  type: evalv2
                  connections: []
                  expr: '`pca/pca_input_data.csv`'
                resource:
                  type: static
                  value: '$res:f/vat_gift_cards/pfm-windmill-vat-gift-cards'
                text:
                  type: static
                  value: 'Drag and Drop: PCA ''.csv'' file'
            selected: s3
        customCss:
          container:
            class: ''
            style: ''
        onFileChange:
          - bg_0
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 2
        x: 5
        y: 12
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 1
        x: 2
        y: 2
      id: e
      data:
        id: e
        type: buttoncomponent
        actions: []
        componentInput:
          type: runnable
          autoRefresh: false
          fields: {}
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByPath
            name: PCA Data Injection
            path: f/pca/pca_data_injection_flow
            runType: flow
            schema:
              $schema: 'https://json-schema.org/draft/2020-12/schema'
              type: object
              order: []
              properties: {}
              required: []
        configuration:
          afterIcon:
            type: static
            value: activity
          beforeIcon:
            type: static
            value: syringe
          color:
            type: static
            value: blue
          confirmationModal:
            type: oneOf
            configuration:
              confirmationModal:
                description:
                  type: static
                  value: Are you sure?
                confirmationText:
                  type: static
                  value: Confirm
                title:
                  type: static
                  value: Title
              none: {}
            selected: confirmationModal
          disabled:
            type: static
            value: false
          fillContainer:
            type: static
            value: false
          label:
            type: static
            value: Inject PCA data into database
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: An error occured
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: Finished injecting PCA data!
              setTab:
                setTab:
                  type: static
                  value: []
            selected: sendToast
          size:
            type: static
            value: md
          triggerOnAppLoad:
            type: static
            value: false
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds:
          - bg_0
        verticalAlignment: center
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  norefreshbar: false
  subgrids:
    a-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 2
          w: 12
          x: 0
          y: 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          y: 0
        id: b
        data:
          id: b
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections: []
            eval: PCA File Uploader (CSV)
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: publisher
  triggerables_v2:
    'e:flow/f/pca/pca_data_injection_flow':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs: {}
